### ISSUE TITLE
Webfrontend: Export to CSV does not work

### ISSUE THREAD

**Issue by lwiniwar** [3dgeo-heidelberg/pytreedb#38]
In GitLab by @JannikaSchaefer on Mar 16, 2022, 13:11

Nothing happens if I click on the button.

**Comment by annachiu7** [comment]
This should work now

**Comment by annachiu7** [comment]
Does it still not work after updating the webserver?

**Comment by lwiniwar** [comment]
Current error (on webserver side):
```
- - [29/Mar/2022 09:28:47] "POST /exportcsv HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/opt/miniconda3/envs/pytreedb/lib/python3.9/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/miniconda3/envs/pytreedb/lib/python3.9/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/miniconda3/envs/pytreedb/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/miniconda3/envs/pytreedb/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/miniconda3/envs/pytreedb/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/miniconda3/envs/pytreedb/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/var/www/pytreedb/webserver/pytreedb_server/__main__.py", line 109, in exportcsv
    mydb.convert_to_csv(outdir, trees)
  File "/var/www/pytreedb/pytreedb/db.py", line 588, in convert_to_csv
    data = self[trees]
  File "/var/www/pytreedb/pytreedb/db.py", line 93, in __getitem__
    return list(self.db[key] for key in item)
  File "/var/www/pytreedb/pytreedb/db.py", line 93, in <genexpr>
    return list(self.db[key] for key in item)
TypeError: list indices must be integers or slices, not dict

```

**Comment by annachiu7** [comment]
I adapted the request method to the lastly changed csv-converting method by Hannah.. It really should work now I hope. @lwiniwar could you plz update the webserver again? thx

**Comment by lwiniwar** [comment]
webserver updated, seems to work.
